concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "F4350-CHWZM33-L"
  url = "https://gitlab.com"
  token = "EpLdeh7JoK4xG5xt2_yv"
  executor = "shell"
  shell = "powershell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
